{"name": "Test of failed attempt to get user orders without authorization", "status": "passed", "description": "Negative test of the endpoint \"Получение заказов конкретного пользователя\" GET /api/orders.Checks that response code is 401 that response body contains all required fieldsand that request returns \"success\": false", "start": 1719670151770, "stop": 1719670153214, "uuid": "a53c9eb1-c78b-49d7-8e23-c1e8df8ca17e", "historyId": "93377173a641d4dfe08f02262c107afc", "testCaseId": "93377173a641d4dfe08f02262c107afc", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_user_orders_without_authorization_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-4KK18J8"}, {"name": "thread", "value": "600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}